### PR TITLE
Add the ability to save sort criteria

### PR DESCRIPTION
**Pull request by ghpeppe**
Very useful and easy to use extension. I've added the ability to save sort criteria.

### CODE REVIEW

**Comment by marqu3s** [comment]
Hi ghpeppe! Thanks for your contribution. I'll review your code soon.

**Comment by marqu3s** [comment]
Question: Why did you change composer.json? I can't keep your username in the places where you replaced mine because of BC. Will change it back to mine ok?

**Comment by ghpeppe** [comment]
Sure. I'm new about composer, and github too, so I made confusion. Sorry.

**Comment by marqu3s** [comment]
That's fine! I have a request. Please add convertGridSort() function as a static function in your SaveGridOrderBehavior class and replace references to GenLib::convertGridSort() to SaveGridOrderBehavior::convertGridSort().
This way we keep all the needed code together.

**Pull request merged**
